SOFLAGS = -fPIC
LDSOFLAGS = -shared
LDDLFLAGS = -shared
CC = gcc
LD = gcc
CFLAGS = -Wextra -static -g -O2 -Wall  -DHAVE_CONFIG  -std=gnu11 -pipe -Wall -Wshadow -Wcast-align -Wpointer-arith -Wwrite-strings -Wundef -Wmissing-prototypes -Wredundant-decls -Wextra -Wno-sign-compare -Wformat-security -Wold-style-definition -Wno-pointer-sign -Werror-implicit-function-declaration -Wno-unused-parameter -Wno-missing-field-initializers -MMD -MP -MF .dep-$(subst /,-,$@) -DREALTIME_SCHEDULING
LDFLAGS =  
HOSTCC = gcc
HOSTLD = gcc
HOST_CFLAGS = -g -O2 -Wall
HOST_LDFLAGS = 
COMPAT_LIBS = 
DL_CFLAGS = 
DL_LIBS = -ldl -Wl,--export-dynamic
PTHREAD_CFLAGS = -D_REENTRANT
PTHREAD_LIBS = -lpthread
PKG_CONFIG = /usr/bin/pkg-config
NCURSES_CFLAGS = -D_GNU_SOURCE -D_DEFAULT_SOURCE -I/usr/include/ncursesw 
NCURSES_LIBS = -lncursesw -ltinfo
ICONV_CFLAGS = 
ICONV_LIBS = 
CDIO_CFLAGS = 
CDIO_LIBS = -lcdio_cdda -lcdio -lm
FFMPEG_CFLAGS = -I/usr/include/x86_64-linux-gnu
FFMPEG_LIBS = -lavformat -lavcodec
PULSE_CFLAGS = -D_REENTRANT
PULSE_LIBS = -lpulse
ALSA_CFLAGS = -I/usr/include/alsa
ALSA_LIBS = -lasound
SNDIO_CFLAGS = 
SNDIO_LIBS = -lsndio
bindir = /usr/local/bin
datadir = /usr/local/share
libdir = /usr/local/lib
mandir = /usr/local/share/man
exampledir = /usr/local/share/doc/cmus/examples
CONFIG_AAC = n
CONFIG_ALSA = y
CONFIG_AO = y
CONFIG_ARTS = n
CONFIG_CDIO = n
CONFIG_COREAUDIO = n
CONFIG_CUE = n
CONFIG_FFMPEG = y
CONFIG_FLAC = y
CONFIG_JACK = n
CONFIG_MAD = n
CONFIG_MIKMOD = n
CONFIG_MODPLUG = n
CONFIG_MP4 = n
CONFIG_MPC = n
CONFIG_MPRIS = n
CONFIG_OPUS = n
CONFIG_OSS = n
CONFIG_PULSE = y
CONFIG_ROAR = n
CONFIG_SAMPLERATE = n
CONFIG_SNDIO = y
CONFIG_SUN = n
CONFIG_VORBIS = n
CONFIG_VTX = n
CONFIG_WAV = n
CONFIG_WAVEOUT = n
CONFIG_WAVPACK = n
GINSTALL = install
topdir = /home/silky/projects/cmus
