#!/usr/bin/env sh

REPODIR=$(pwd)
TMPDIR=$1

# setup bash env
echo 'setup bashrc'
cp $REPODIR/bash/bashrc ~/.bashrc
cp $REPODIR/bash/aliases ~/.bash_aliases

# create user bin folder
mkdir ~/bin/

# setup vim
echo 'setup vim'
sh $REPODIR/vim/setup_vim

# setup hastebin scripts
echo 'setup hastebin'
cp $REPODIR/hastebin/* ~/bin

# copy dwm init script to user bin folder
# and dwm entry for lightdm
echo 'setup dwm'
cp $REPODIR/dwm/dwm_init ~/bin/dwm_init
cp $REPODIR/dwm/dwm.desktop /usr/share/xsessions/dwm.desktop

# create temporary setup folder
mkdir $TMPDIR

# install Hermit font
echo 'setup hermit font'
mkdir $TMPDIR/hermit
cd $TMPDIR/hermit
wget https://pcaro.es/d/otf-hermit-1.21.tar.gz
tar xvzf *hermit*.tar.gz
sudo mkdir -p /usr/share/fonts/opentype/hermit
sudo cp *.otf /usr/share/fonts/opentype/hermit

# clone git repos
cd $TMPDIR

echo 'cloning repositories'
git clone http://git.suckless.org/st
git clone http://git.suckless.org/dwm
git clone http://git.suckless.org/dmenu
git clone https://github.com/drkh5h/slstatus

echo 'copying config files'
cp -f $REPODIR/st/* $TMPDIR/st
cp -f $REPODIR/dwm/* $TMPDIR/dwm
cp -f $REPODIR/dmenu/* $TMPDIR/dmenu
cp -f $REPODIR/slstatus/* $TMPDIR/slstatus
