#!/usr/bin/env sh

############################################################
REPODIR=$(pwd)
SETUPDIR=$REPODIR/.setup
mkdir -m 0700 -p $HOME/.config/stuff

# disable mouse accel
sudo cp $REPODIR/xorg/50-mouse-acceleration.conf /usr/share/X11/xorg.conf.d/

# setup bash env
wget -nv --show-progress -O $HOME/.config/stuff/dircolors https://raw.githubusercontent.com/trapd00r/LS_COLORS/master/LS_COLORS
wget -nv --show-progress -O $HOME/.config/stuff/git-prompt.sh https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh

# create folder for abduco sessions if $ABDUCO_SOCKET_DIR exists
[ "$ABDUCO_SOCKET_DIR" != "" ] && [ ! -d $ABDUCO_SOCKET_DIR ] && mkdir -p -m 0700 "$ABDUCO_SOCKET_DIR"

# create user bin folder
[ ! -d $HOME/bin ] && mkdir -m 0700 $HOME/bin

############################################################
VIMFILES=$HOME/.vim
SWP=$VIMFILES/swp
AUTO=$VIMFILES/autoload

# create necessary folders in ~/.vim
mkdir -m 0700 -p $SWP $AUTO

# get Vim-Plug
wget -nv --show-progress -O $AUTO/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

############################################################
# setup newsbeuter
mkdir -m 0700 -p $HOME/.local/share/newsbeuter

############################################################
# set up pomodoro
git clone https://github.com/rukshn/pomodoro $HOME/.config/pomodoro

############################################################
# create temporary setup folder
mkdir -m 0700 -p $SETUPDIR/hermit

# install Hermit font
cd $SETUPDIR/hermit
wget -nv --show-progress -O hermit.tar.gz 'https://pcaro.es/d/otf-hermit-1.21.tar.gz'
tar xvzf hermit.tar.gz
sudo mkdir -p /usr/share/fonts/opentype/hermit
sudo cp $SETUPDIR/hermit/*.otf /usr/share/fonts/opentype/hermit

# copy dwm entry for lightdm
sudo cp $REPODIR/repos/dwm/dwm.desktop /usr/share/xsessions/

############################################################
# clone git repos
cd $SETUPDIR

git clone http://git.suckless.org/dmenu
git clone http://git.suckless.org/dwm
git clone http://git.suckless.org/slock
git clone http://git.suckless.org/st
git clone http://git.suckless.org/tabbed
git clone https://github.com/drkh5h/slstatus
git clone https://github.com/martanne/abduco
git clone https://github.com/martanne/dvtm
git clone https://github.com/BurntSushi/ripgrep

[ -f dmenu/dmenu_path ] && rm dmenu/dmenu_path
[ -f dmenu/dmenu_run ] && rm dmenu/dmenu_run

############################################################
cd $REPODIR
# dry run
stow -nv -t $HOME home
stow -nv -t $SETUPDIR repos

echo 'to apply these changes do:'
echo "stow -v -t $HOME home; stow -v -t $SETUPDIR repos"
