#!/usr/bin/env sh

############################################################
REPODIR=$(pwd)
SETUPDIR=$REPODIR/.setup
mkdir -m 0700 -p $HOME/.config/stuff

# disable mouse accel
cp $REPODIR/xorg/50-mouse-acceleration.conf /usr/share/X11/xorg.conf.d/

# setup bash env
wget -nv --show-progress -O $HOME/.config/stuff/dircolors https://raw.githubusercontent.com/trapd00r/LS_COLORS/master/LS_COLORS
wget -nv --show-progress -O $HOME/.config/stuff/git-prompt.sh https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh

# create folder for abduco sessions if $ABDUCO_SOCKET_DIR exists
[ "$ABDUCO_SOCKET_DIR" != "" ] && [ ! -d "$ABDUCO_SOCKET_DIR" ] && mkdir -p -m 0700 "$ABDUCO_SOCKET_DIR"

# create user bin folder
[ ! -d $HOME/bin ] && mkdir -m 0700 $HOME/bin

############################################################
VIMFILES=$HOME/.vim
SWP=$VIMFILES/swp
AUTO=$VIMFILES/autoload

# create necessary folders in ~/.vim
mkdir -m 0700 -p $SWP $AUTO

# get Vim-Plug
wget -nv --show-progress -O $AUTO/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

############################################################
# setup newsbeuter
mkdir -m 0700 -p $HOME/.local/share/newsbeuter

############################################################
# create temporary setup folder
mkdir -m 0700 -p $SETUPDIR/hermit

# install Hermit font
cd $SETUPDIR/hermit
wget -nv --show-progress -O hermit.tar.gz 'https://pcaro.es/d/otf-hermit-2.0.tar.gz' \
&& echo "ee41f8cbcdedfff568cd47ab7730c462ddd67d6170c05d35eaf64a7f954a4bb72d6ac99a383749f7032d9cf7b407b7a5ef3270b4209692c1572beb9744a21d42 *hermit.tar.gz" | sha512sum -c - && {
tar xvzf hermit.tar.gz
mkdir -p /usr/share/fonts/opentype/hermit
cp $SETUPDIR/hermit/*.otf /usr/share/fonts/opentype/hermit
}

# copy dwm entry for lightdm
cp $REPODIR/repos/dwm/dwm.desktop /usr/share/xsessions/

############################################################
# clone git repos
cd $SETUPDIR

for REPO in \
    https://git.suckless.org/dmenu            \
    https://git.suckless.org/dwm              \
    https://git.suckless.org/slock            \
    https://git.suckless.org/st               \
    https://git.suckless.org/tabbed           \
    https://github.com/arzzen/git-quick-stats \
    https://github.com/cmus/cmus              \
    https://github.com/drkhsh/slstatus        \
    https://github.com/martanne/abduco        \
    https://github.com/martanne/dvtm          \
    https://github.com/siiky/c-utils          \
    https://github.com/universal-ctags/ctags  \
    ; do
git clone --depth=1 "$REPO"
done

[ -f dmenu/dmenu_path ] && rm dmenu/dmenu_path
[ -f dmenu/dmenu_run ] && rm dmenu/dmenu_run
[ -f $REPODIR/install.sh ] && cp $REPODIR/install.sh $SETUPDIR

############################################################
cd $REPODIR
# dry run
stow -nv -t $HOME home
stow -nv -t $SETUPDIR repos

echo 'to apply these changes do:'
echo "stow -v -t $HOME home; stow -v -t $SETUPDIR repos"
