#!/usr/bin/env sh

VIMFILES=~/.vim
SWP=$VIMFILES/swp
AUTO=$VIMFILES/autoload

# create necessary folders in ~/.vim
mkdir -p $SWP $AUTO

# get Vim-Plug
wget -q -O $AUTO/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

cp ./vimrc $VIMFILES/vimrc
vim -c "PlugInstall"
