#!/usr/bin/env sh

# keyboard layout
# `$ grep "grp:.*toggle" /usr/share/X11/xkb/rules/base.lst`
# -layout pt                    PT layout
# -layout us                    US layout
# -option ctrl:nocaps           CAPS => CTRL
# -option grp:sclk_toggle       SCR_LK to switch between layouts
exec setxkbmap -layout us -option ctrl:nocaps &

# disable mouse accel
exec xset m 0 0 &

# status bar
ps -C slstatus > /dev/null || exec slstatus || xsetroot -name ' ' &
#pgrep xautolock > /dev/null || exec xautolock -time 10 -locker slock -killtime 5 -killer "systemctl suspend" -bell 0 -noclose &
#pgrep redshift > /dev/null || exec redshift &

# JP IME
#export GTK_IM_MODULE='fcitx'
#export QT_IM_MODULE='fcitx'
#export XMODIFIERS='@im=fcitx'

xrandr --output HDMI-A-0 --auto --output DisplayPort-0 --auto --right-of HDMI-A-0

[ -f ~/.config/stuff/fehbg ] && . ~/.config/stuff/fehbg
export PATH=$HOME/bin:$HOME/.local/bin/:$HOME/.luarocks/bin/:$PATH
export WINIT_HIDPI_FACTOR=1
export CALIBRE_USE_DARK_PALETTE=1
exec dwm
