#!/usr/bin/env sh

# keyboard layout
# `$ grep "grp:.*toggle" /usr/share/X11/xkb/rules/base.lst`
# set PT as default and bind scroll lock to toggle between layouts
exec setxkbmap -layout pt,us -option grp:sclk_toggle &
# cmqfr
#exec setxkbmap -device 12 -device 13 -layout us &
# 15-key pad
#exec setxkbmap -device 18 -layout us &

exec xset m 0 0 & # disable mouse accel

pgrep redshift > /dev/null || exec redshift &
pgrep slstatus > /dev/null || exec slstatus -d || xsetroot -name ' ' & # status bar
pgrep xautolock > /dev/null || exec xautolock -time 10 -locker slock -killtime 5 -killer "systemctl suspend" -bell 0 -noclose & 

# set wallpaper with feh
[ -f ~/.config/stuff/fehbg ] && . ~/.config/stuff/fehbg

exec xmodmap ~/.config/stuff/xmodmap &
#exec oneko -tora -tofocus -bg black -fg red &

# run the DWM window manager
exec dwm
