#!/usr/bin/env sh

# keyboard layout
# `$ grep "grp:.*toggle" /usr/share/X11/xkb/rules/base.lst`
# -layout pt                    PT layout
# -layout us                    US layout
# -option ctrl:nocaps           CAPS => CTRL
# -option grp:sclk_toggle       SCR_LK to switch between layouts
# If external KB set US as default, else PT
(xinput list | grep -qs QuickFire && exec setxkbmap -layout us,pt -option ctrl:nocaps -option grp:sclk_toggle) || exec setxkbmap -layout pt,us -option ctrl:nocaps -option grp:sclk_toggle &

# disable mouse accel
exec xset m 0 0 &

# status bar
pgrep slstatus > /dev/null || exec slstatus -d || xsetroot -name ' ' &
pgrep xautolock > /dev/null || exec xautolock -time 10 -locker slock -killtime 5 -killer "systemctl suspend" -bell 0 -noclose & 
pgrep redshift > /dev/null || exec redshift &

# set wallpaper with feh
[ -f ~/.config/stuff/fehbg ] && . ~/.config/stuff/fehbg

#exec oneko -tora -tofocus -bg black -fg red &

# JP IME
#export GTK_IM_MODULE='fcitx'
#export QT_IM_MODULE='fcitx'
#export XMODIFIERS='@im=fcitx'

# run the DWM window manager
exec dwm
